version: '3.8'

services:
  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: superman
      POSTGRES_PASSWORD: batman
      POSTGRES_DB: wordle
    ports:
      - '6666:5432'
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
